apiVersion: apps/v1
kind: Deployment
metadata:
  name: agents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agents
  template:
    metadata:
      labels:
        app: agents
    spec:
      containers:
        - name: agents
          image: mohamediliasskaddar/e-commerce-agents:latest
          imagePullPolicy: Always
          env:
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: minio-config
                  key: endpoint
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secret-key
            - name: MINIO_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: minio-config
                  key: bucket
            - name: MINIO_SECURE
              value: "true"
            - name: DATA_PATH
              value: "/app/data"
          volumeMounts:
            # Optional: local cache for faster reads
            - name: cache-volume
              mountPath: /app/data
      volumes:
        - name: cache-volume
          emptyDir:
            sizeLimit: 5Gi