apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
        - name: pipeline
          image: mohamediliasskaddar/e-commerce-pipeline:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc